apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'Jenkins'
  description: 'a description'
  annotations:
    jenkins.io/job-full-name: ATC-Training-API/dev
spec:
  type: service
  lifecycle: experimental
  owner: your-name
