---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'This Template creates EKS CLUSTER NODE IAM ROLE'


Parameters:

  eksNodeRoleName:
    Type: String

Resources:

  eksNodeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns: 
      - "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
      - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      - "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
Outputs:

  RoleArn:
    Description: The role that Amazon EKS will use to create AWS resources for Kubernetes clusters
    Value: !GetAtt eksNodeRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-RoleArn"